# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

steps:
  - task: AzureCLI@2
    displayName: 'Terraform validate'
    inputs:
      azureSubscription: '$(ado_service_connection_rg)'
      scriptType: 'bash'
      addSpnToEnvironment: true
      workingDirectory: '$(System.DefaultWorkingDirectory)/$(terraform_workingdir)'
      scriptLocation: 'inlineScript'
      inlineScript: |
        terraform validate