# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
  - name: azureServiceConnection
    type: string
    default: '$(ado_service_connection_rg)'
  - name: workingDirectory
    type: string
    default: '$(System.DefaultWorkingDirectory)/$(terraform_workingdir)'
  - name: planFile
    type: string
    default: tfplan

steps:
  - task: AzureCLI@2
    displayName: 'Terraform apply'
    inputs:
      azureSubscription: ${{ parameters.azureServiceConnection }}
      scriptType: 'bash'
      addSpnToEnvironment: true
      workingDirectory: ${{ parameters.workingDirectory }}
      scriptLocation: 'inlineScript'
      inlineScript: |
        set -euo pipefail
        export ARM_USE_OIDC=true
        export ARM_OIDC_TOKEN="$idToken"
        export ARM_CLIENT_ID="$servicePrincipalId"
        export ARM_TENANT_ID="$tenantId"
        export ARM_SUBSCRIPTION_ID
        ARM_SUBSCRIPTION_ID="$(az account show --query id --output tsv)"

        terraform apply -input=false -auto-approve "$TF_PLAN_FILE"
    env:
      TF_PLAN_FILE: ${{ parameters.planFile }}
