# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
  - name: azureServiceConnection
    type: string
    default: '$(ado_service_connection_rg)'
  - name: workingDirectory
    type: string
    default: '$(System.DefaultWorkingDirectory)/$(terraform_workingdir)'

steps:
  - task: AzureCLI@2
    displayName: 'Terraform validate'
    inputs:
      azureSubscription: ${{ parameters.azureServiceConnection }}
      scriptType: 'bash'
      addSpnToEnvironment: true
      workingDirectory: ${{ parameters.workingDirectory }}
      scriptLocation: 'inlineScript'
      inlineScript: |
        set -euo pipefail
        terraform fmt -check -recursive
        terraform validate